echo off
cls
echo                                  ALTKEYS.BAT
echo.
echo.
echo                            Aguarde por favor . . .
Rem ALT e A
esc [0;30;"Attrib "p
Rem ALT e B
esc [0;48;"Backup "p
Rem ALT e C
esc [0;46;"Copy "p
Rem ALT e D
esc [0;32;"Dir "p
Rem ALT e E
esc [0;18;"Exit";13p
Rem ALT e F
esc [0;33;"Format "p
Rem ALT e G
esc [0;34;"GWBASIC";13p
Rem ALT e H
esc [0;35;" "p
Rem ALT e I
esc [0;23;" "p
Rem ALT e J
esc [0;36;"Join "p
Rem ALT e K
esc [0;37;" "p
Rem ALT e L
esc [0;38;"Label "p
Rem ALT e M
esc [0;50;" "p
Rem ALT e N
esc [0;49;" "p
Rem ALT e O
esc [0;24;" "p
Rem ALT e P
esc [0;25;"Print "p
Rem ALT e Q
esc [0;16;" "p
Rem ALT e R
esc [0;19;"Rename "p
Rem ALT e S
esc [0;31;"Sort "p
Rem ALT e T
esc [0;20;"Type "p
Rem ALT e U
esc [0;22;" "p
Rem ALT e V
esc [0;47;" "p
Rem ALT e W
esc [0;17;" "p
Rem ALT e X
esc [0;45;"XCopy "p
Rem ALT e Y
esc [0;44;" "p
Rem ALT e Z
esc [0;21;" "p
